name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
jobs:
  build:
    runs-on: 
    - self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a one-line script
        run: echo Hello, world!
      - name: Run a multi-line script
        run: |
          wget https://www.chiark.greenend.org.uk/~sgtatham/putty/latest.html
          echo Add other actions to build,
          echo test, and deploy your project.
